services:
  DeabreuAPI:
    build: "./DeabreuAPI"
    container_name: DeabreuAPI
    environment:
      DB_HOST: db
      DB_DATABASE: deabreu
      DB_USERNAME: patrick
      DB_PASSWORD: patrick
    ports:
      - 8000:8000
    volumes:
      - ./DeabreuAPI:/app/DeabreuAPI
      - /app/DeabreuAPI/vendor
    depends_on:
      - db
    networks:
      - app

  DeabreuPainel:
    build: "./DeabreuPainel"
    container_name: DeabreuPainel
    tty: true
    ports:
      - 3001:3001
    volumes:
      - ./DeabreuPainel:/app/DeabreuPainel
      - /app/DeabreuPainel/node_modules
    depends_on:
      - backend
    networks:
      - app

  DeabreuStore:
    build: "./DeabreuStore"
    container_name: DeabreuStore
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./DeabreuStore:/app/DeabreuStore
      - /app/DeabreuStore/node_modules
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mysql:8.0
    container_name: DeabreuDB
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'deabreu'
      MYSQL_USER: 'patrick'
      MYSQL_PASSWORD: 'patrick'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - deabreu_mysql:/var/lib/mysql
    networks:
      - app

volumes:
  deabreu_mysql_data:

networks:
  app:
    driver: bridge