import type { Metadata } from "next";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Box, CssBaseline, Toolbar } from "@mui/material";
import Sidebar from "@/components/Sidebar";
import TokenChecker from '../../components/TokenChecker';

export const metadata: Metadata = {
  title: "Painel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Box sx={{ display: "flex" }}>
          <CssBaseline />
          <Sidebar />
          <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
            <Toolbar />
            <TokenChecker />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
