import type { Metadata } from "next";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { Fab } from "@mui/material";
import WhatsAppIcon from '@mui/icons-material/WhatsApp';
import "slick-carousel/slick/slick.css"; // Importa o CSS do react-slick
import "slick-carousel/slick/slick-theme.css"; // Importa o tema do react-slick

export const metadata: Metadata = {
  title: "Deabreu Veiculos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <Fab sx={{
          position: "fixed",
          right: "0",
          bottom: "0",
          margin: "0 15px 15px 0",
          backgroundColor: "#e0c000",
          "&:hover": {
            backgroundColor: "#af9500" 
          }
        }} aria-label="edit">
          <WhatsAppIcon sx={{color: "white", fontSize: "30px"}}/>
        </Fab>
      </body>
    </html>
  );
}
